Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/MethodLength:
  Max: 20

require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'